var express=require("express")
var router= express.Router()
var productNormalcontroller=require("../controllers/productNormalcontroller")
var authenticate=require("../middleware/authenticate")
router.get("/shoes/men",productNormalcontroller.renderMenshoespage)
router.get("/shoes/women",productNormalcontroller.renderwomenshoespage)
router.get("/shoes/kids",productNormalcontroller.renderkidshoespage)
router.get("/success",productNormalcontroller.exitpage)
router.get("/shoes/men/:shoeId",productNormalcontroller.productdetails)
router.get("/shoes/women/:shoeId",productNormalcontroller.productdetails)
router.get("/shoes/kids/:shoeId",productNormalcontroller.productdetails)
router.get("/shoes/men/addtocart/:shoeId",authenticate,productNormalcontroller.addtocart)
router.get("/shoes/women/addtocart/:shoeId",authenticate,productNormalcontroller.addtocart)
router.get("/shoes/kids/addtocart/:shoeId",authenticate,productNormalcontroller.addtocart)
router.get("/cart",authenticate,productNormalcontroller.cart)
router.get("/exitpage",authenticate,productNormalcontroller.exitpage)
module.exports=router